This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Applications/MAMP/htdocs/securecoding/tum-thesis-latex-master/.texpadtmp/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Applications/MAMP/htdocs/securecoding/tum-thesis-latex-master/.texpadtmp/main.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file /Applications/MAMP/htdocs/securecoding/tum-thesis-latex-master/.texpadtmp/main.acr....done (6 lines written, 0 warnings).
Output written in /Applications/MAMP/htdocs/securecoding/tum-thesis-latex-master/.texpadtmp/main.acr.
Transcript written in /Applications/MAMP/htdocs/securecoding/tum-thesis-latex-master/.texpadtmp/main.alg.
