This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/stefankofler/securecoding/SecureCoding-Group3/tum-thesis-latex-master/.texpadtmp/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/stefankofler/securecoding/SecureCoding-Group3/tum-thesis-latex-master/.texpadtmp/main.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file /Users/stefankofler/securecoding/SecureCoding-Group3/tum-thesis-latex-master/.texpadtmp/main.acr....done (6 lines written, 0 warnings).
Output written in /Users/stefankofler/securecoding/SecureCoding-Group3/tum-thesis-latex-master/.texpadtmp/main.acr.
Transcript written in /Users/stefankofler/securecoding/SecureCoding-Group3/tum-thesis-latex-master/.texpadtmp/main.alg.
